export const SkillData =  [
    {name:"html",
     prof : 96,
     image:'html.png',
     directionLeft:false,   
    },
    {name:"css",
     prof : 95,
     image:'Css.png',
     directionLeft:false,   
    },
    {name:"tailwind",
     prof : 90,
     image:'tailwind.png',
     directionLeft:false,   
    },
    {name:"javascript",
     prof : 92,
     image:'javascript.png',
     directionLeft:false,   
    },
    {name:"react",
     prof : 97,
     image:'react-icon-small.png',
     directionLeft:false,
     style:"animate-spin-slow"   
    },
    // {name:"nextJs",
    //  prof : 92,
    //  image:'nextjs-logo.png',
    //  directionLeft:true,   
    // },
    {name:"dsa",
     prof : 56,
     image:'dsa.png',
     directionLeft:true, 
     style:"invert"  
    },
    {name:"firebase",
     prof : 83,
     image:'Firebase.png',
     directionLeft:true,   
    },
    {name:"github",
     prof : 72,
     image:'github_2.png',
     directionLeft:true,   
    },
    {name:"vscode",
     prof : 92,
     image:'vscode.png',
     directionLeft:true,   
    },
    {name:"python",
     prof : 90,
     image:'python.png',
     directionLeft:true,   
    },
]